import "@/styles/globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import SupabaseProvider from "@/providers/SupabaseProvider";
import UserProvider from "@/providers/UserProvider";
import ToasterProvider from "@/providers/ToasterProvider";
import Realtime from "@/components/modals/realtime";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "varthaCMS | 📰 News CMS",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex-col flex">
          <ToasterProvider />
          <SupabaseProvider>
            <UserProvider>
              <Realtime />
              <Navbar />
              {children}
            </UserProvider>
          </SupabaseProvider>
        </div>
      </body>
    </html>
  );
}
